import '../globals.css'
//implementar font awesome icons
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  brandName: 'Barb & Heimer',
}

export default function RootLayout({ children }) {
  return (
    <div>
      <div className="brand-name">{metadata.brandName}</div>
      <div className="navigation-bar">
        <p className="texto-navigation-bar">Todos</p>
        <p className="texto-navigation-bar">Ojos</p>
        <p className="texto-navigation-bar">Cabello</p>
        <p className="texto-navigation-bar">Uñas</p>
      </div>
      {children}
    </div>
  )
}
