"use client"
import React from 'react';
import './globals.css'
//import { Inter } from 'next/font/google'

//implementar font awesome icons
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Link from "next/link";
import { createContext, useContext, useState, useEffect } from 'react';
import { getUser } from "@/app/services/axiosAPIServices";
import { usePathname } from 'next/navigation';
import PropTypes from 'prop-types';

config.autoAddCss = false;

const BolsaComprasContext = createContext();

export const useBolsaComprasContext = () => {
  return useContext(BolsaComprasContext);
};

const ProductosCompradosContext = createContext();

export const useProductosCompradosContext = () => {
  return useContext(ProductosCompradosContext);
};

const MetodoPagoContext = createContext();

export const useMetodoPagoContext = () =>{
  return useContext(MetodoPagoContext);
}

//const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  brandName: 'Bodoni Moda',
}

//const categorias = ["Todos", "Skin Care", "Labios", "Cabello", "Ojos", "Accesorios", "Piel"];

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};


export default function RootLayout({ children }) {
  const [listaBolsaCompras, setListaBolsaCompras] = useState([]);
  const [productosComprados, setProductosComprados] = useState([])
  const [metodoPago, setMetodoPago] = useState(1);
  //const [selectedCategory, setSelectedCategory] = useState("Todos");

  const path = usePathname();

  const [user, setUser] = useState(null)
  useEffect(() => {
    const getUserData = async () => {
      const user = await getUser();
      setUser(user.data)
    };

    getUserData();
  },[])
  
  return (
    <html lang="en">
      <body style={{backgroundColor: '#F9F8F7'}}>
        <div className="w-full flex flex-row items-center justify-center" style={{backgroundColor:"var(--primary-def)", gap:"12.25em"}}>
          <div className="flex flex-row items-center justify-center" style={{width:"33%"}}></div>
          <div className="brand-name flex-nowrap whitespace-nowrap" style={{width:"33%"}}>{metadata.brandName}</div>
          <div className="flex flex-row items-center justify-center" style={{width:"33%"}}>
            
            {
              path != "/login" &&
              <Link href={"/profile"} className="flex p-3 gap-2 flex-nowrap" style={{ maxWidth:"45%", overflow:"hidden", textOverflow:"ellipsis",marginLeft:'12em'}}>
                <img style={{ width:"2.5em", height: "2.5em", backgroundColor: '#d9d9d9', borderRadius: 100,borderWidth:3, borderColor:"var(--primary-100)",}} src={user? user.image : "\tame-impala.jpg"} alt="Cliente" />
                
              </Link>
            }
            
          </div>
          
        </div>
      <ProductosCompradosContext.Provider value={{productosComprados, setProductosComprados}}>
      <BolsaComprasContext.Provider value={{listaBolsaCompras, setListaBolsaCompras}}>
        <MetodoPagoContext.Provider value={{metodoPago, setMetodoPago}}>
      {children}
      </MetodoPagoContext.Provider>
      </BolsaComprasContext.Provider>
      </ProductosCompradosContext.Provider>
      </body>
    </html>
  )
}
