import './globals.css'
import { Inter } from 'next/font/google'

//implementar font awesome icons
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  brandName: 'Barb & Heimer',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="brand-name">{metadata.brandName}</div>
      {children}
      </body>
    </html>
  )
}
